// Generated by `pnpm --filter @oakoss/tokens generate` from the token data.
export const cnTheme = {
  font: ['heading', 'mono', 'sans'],
  radius: ['badge', 'control', 'panel'],
  spacing: [
    'badge',
    'control',
    'control-lg',
    'control-sm',
    'control-x',
    'panel',
    'popover',
  ],
  text: ['2xl', '3xl', '4xl', 'base', 'lg', 'sm', 'ui', 'xl', 'xs'],
};
