import type { Family, Polarity } from '#/family';
import type { Style } from '#/style';

import {
  type Declarations,
  fieldColor,
  formatColor,
  primaryTokenNames,
  resolved,
  rule,
  tokenDeclarations,
} from '#/css';

const header =
  '/* Generated by @oakoss/tokens (pnpm --filter @oakoss/tokens generate). Do not edit. */';

/**
 * Every family and primary hue, scoped by `data-family` and `data-primary`
 * for runtime switching. Blocks hold resolved values rather than aliases, so
 * a scope never depends on variables declared further up.
 */
export function bundleCss(families: readonly Family[], style: Style): string {
  const blocks: string[] = [header];
  for (const family of families) {
    for (const polarity of ['light', 'dark'] as const) {
      const tokens = resolved(family, polarity);
      blocks.push(
        rule(selector('data-family', family.id, polarity), [
          ['--field', fieldColor(style, polarity, tokens)],
          ...tokenDeclarations(tokens),
        ]),
      );
    }
  }
  // Primary blocks come after family blocks: on one element they tie on
  // specificity, and the later block's primary wins.
  for (const hue of primaryHues(families)) {
    for (const polarity of ['light', 'dark'] as const) {
      blocks.push(
        rule(
          selector('data-primary', hue, polarity),
          primaryDeclarations(families, hue, polarity),
        ),
      );
    }
  }
  return blocks.join('\n\n');
}

// Axis independence (note 0004): a primary hue must resolve to the same
// values in every family that offers it, or one block can't serve them all.
function primaryDeclarations(
  families: readonly Family[],
  hue: string,
  polarity: Polarity,
): Declarations {
  const offering = families.filter((family) =>
    family.intents.primary.choices.includes(hue),
  );
  const [first, ...rest] = offering.map((family) => {
    const tokens = resolved(family, polarity, hue);
    // Optional steps (25, 1000) appear only where a scale has them.
    return primaryTokenNames(family).flatMap((name) => {
      const color = tokens[name];
      return color === undefined
        ? []
        : [[`--${name}`, formatColor(color)] as const];
    });
  });
  if (first === undefined) throw new Error(`no family offers "${hue}"`);
  const expected = JSON.stringify(first);
  for (const [index, declarations] of rest.entries()) {
    if (JSON.stringify(declarations) !== expected) {
      throw new Error(
        `primary "${hue}" (${polarity}) differs in family "${offering[index + 1]?.id}"`,
      );
    }
  }
  return first;
}

function primaryHues(families: readonly Family[]): string[] {
  return [
    ...new Set(families.flatMap((family) => family.intents.primary.choices)),
  ];
}

// `.dark` may sit on the element or on an ancestor such as `<html>`.
function selector(attribute: string, value: string, polarity: Polarity) {
  const scope = `[${attribute}="${value}"]`;
  return polarity === 'light' ? scope : `.dark ${scope}, ${scope}.dark`;
}
