import type { Style } from '#/style';
import type { Typography } from '#/typography';

import { styleDeclarations, typographyDeclarations } from '#/css';

export function cnConfigModule(theme: Record<string, string[]>): string {
  return [
    '// Generated by `pnpm --filter @oakoss/tokens generate` from the token data.',
    `export const cnTheme = ${JSON.stringify(theme)};`,
    '',
  ].join('\n');
}

/**
 * Names `cn` must learn for each theme scale it merges by. Without them it
 * keeps both `h-control h-9`, and reads `text-ui` as a color, so
 * `text-ui text-foreground` drops the size.
 */
export function cnTheme(
  styles: readonly Style[],
  typographies: readonly Typography[],
): Record<string, string[]> {
  const names = [
    ...styles.flatMap((style) => styleDeclarations(style).theme),
    ...typographies.flatMap((typography) => typographyDeclarations(typography)),
  ].map(([name]) => name);
  const theme: Record<string, Set<string>> = {};
  for (const name of names) {
    const match = /^--([a-z]+)-(.+)$/u.exec(name);
    if (match === null) throw new Error(`unexpected theme variable ${name}`);
    const [, namespace = '', value = ''] = match;
    // `--text-ui--line-height` is a modifier of `text-ui`, not a utility.
    if (value.includes('--')) continue;
    (theme[namespace] ??= new Set()).add(value);
  }
  return Object.fromEntries(
    Object.entries(theme)
      .toSorted(([a], [b]) => a.localeCompare(b))
      .map(([namespace, values]) => [
        namespace,
        [...values].toSorted((a, b) => a.localeCompare(b)),
      ]),
  );
}
