import type { Color } from '#/color';
import type { Family, Polarity } from '#/family';
import type { Style, StyleColor } from '#/style';
import type { Typography } from '#/typography';

import {
  chartRoles,
  derivedRoleNames,
  intentRole,
  intentRoleKinds,
} from '#/roles';
import { orderedSteps } from '#/scale';
import { resolveTheme, type ThemeTokens } from '#/theme';
import { zIndex } from '#/z-index';

export type Declarations = readonly (readonly [name: string, value: string])[];

// shadcn's expansion of `--radius`, from its CSS-variable updater.
const radiusScale = [
  ['sm', 'calc(var(--radius) * 0.6)'],
  ['md', 'calc(var(--radius) * 0.8)'],
  ['lg', 'var(--radius)'],
  ['xl', 'calc(var(--radius) * 1.4)'],
  ['2xl', 'calc(var(--radius) * 1.8)'],
  ['3xl', 'calc(var(--radius) * 2.2)'],
  ['4xl', 'calc(var(--radius) * 2.6)'],
] as const;

const header =
  '/* Generated by @oakoss/tokens (pnpm --filter @oakoss/tokens generate). Do not edit. */';

export function fieldColor(
  style: Style,
  polarity: Polarity,
  tokens: ThemeTokens,
): string {
  return styleColor(style.colors.field[polarity], tokens);
}

export function formatColor(color: Color): string {
  const { alpha } = color;
  const [l, c, h] = color.components;
  const value = `${round(l)} ${round(c)} ${round(h ?? 0)}`;
  return alpha === undefined || alpha === 1
    ? `oklch(${value})`
    : `oklch(${value} / ${round(alpha * 100)}%)`;
}

/**
Tokens that follow the primary hue: its scale, its roles, the roles derived
from it and, for a primary ramp, the charts.
*/
export function primaryTokenNames(family: Family): string[] {
  const { charts } = family;
  const hasPrimaryCharts =
    charts.kind === 'ramp' && charts.source.intent === 'primary';
  return [
    ...orderedSteps.map((step) => `primary-${step}`),
    ...intentRoleKinds.map((kind) => intentRole('primary', kind)),
    ...derivedRoleNames,
    ...(hasPrimaryCharts ? chartRoles : []),
  ];
}

export function resolved(
  family: Family,
  polarity: Polarity,
  primary?: string,
): ThemeTokens {
  const flavor = family.defaults[polarity];
  const theme =
    flavor === undefined
      ? [`no default ${polarity} flavor`]
      : resolveTheme(family, flavor, primary);
  if ('tokens' in theme) return theme.tokens;
  throw new Error(`family "${family.id}":\n${theme.join('\n')}`);
}

export function rule(selector: string, declarations: Declarations): string {
  const body = declarations
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
  return `${selector} {\n${body}\n}`;
}

// A token named `<x>-<namespace>` drops the suffix: `control-radius` becomes
// `--radius-control`, so the class is `rounded-control`.
export function styleDeclarations(style: Style): {
  root: Declarations;
  theme: Declarations;
} {
  const root: [string, string][] = [];
  const theme: [string, string][] = [];
  for (const [name, token] of Object.entries(style.tokens)) {
    if (token.namespace === null) {
      root.push([`--${name}`, token.value]);
      continue;
    }
    const suffix = `-${token.namespace}`;
    const short = name.endsWith(suffix) ? name.slice(0, -suffix.length) : name;
    theme.push([`--${token.namespace}-${short}`, token.value]);
    if (token.namespace === 'text' && token.lineHeight !== undefined) {
      theme.push([`--text-${short}--line-height`, token.lineHeight]);
    }
  }
  return { root, theme };
}

/**
Colors and the radius scale go through `@theme inline`, so utilities read
the scoped role variables and `--radius`. Style and type tokens use a plain
`@theme`: a scope can override a literal one, but one that refers to another
variable (`--radius-control: var(--radius-md)`) resolves at `:root`, so a
scope has to redeclare it.
*/
export function themeCss(
  family: Family,
  style: Style,
  typography: Typography,
): string {
  const light = resolved(family, 'light');
  const dark = resolved(family, 'dark');
  const styleVars = styleDeclarations(style);
  const field = (polarity: Polarity, tokens: ThemeTokens) =>
    ['--field', fieldColor(style, polarity, tokens)] as const;
  const bridges = Object.keys(light).map(
    (name) => [`--color-${name}`, `var(--${name})`] as const,
  );
  return [
    header,
    rule(':root', [
      ['color-scheme', 'light'],
      ...styleVars.root,
      ...zIndexDeclarations(),
      field('light', light),
      ...tokenDeclarations(light),
    ]),
    rule('.dark', [
      ['color-scheme', 'dark'],
      field('dark', dark),
      ...tokenDeclarations(dark),
    ]),
    rule('@theme inline', [
      ...bridges,
      ['--color-field', 'var(--field)'],
      ...radiusScale.map(
        ([size, value]) => [`--radius-${size}`, value] as const,
      ),
    ]),
    rule('@theme', [...styleVars.theme, ...typographyDeclarations(typography)]),
  ].join('\n\n');
}

export function tokenDeclarations(tokens: ThemeTokens): Declarations {
  return Object.entries(tokens).map(
    ([name, color]) => [`--${name}`, formatColor(color)] as const,
  );
}

export function typographyDeclarations(typography: Typography): Declarations {
  const declarations: [string, string][] = Object.entries(typography.fonts).map(
    ([role, stack]) => [`--font-${role}`, stack],
  );
  for (const [size, text] of Object.entries(typography.scale)) {
    declarations.push(
      [`--text-${size}`, text.size],
      [`--text-${size}--line-height`, text.lineHeight],
    );
    if (text.letterSpacing !== undefined) {
      declarations.push([`--text-${size}--letter-spacing`, text.letterSpacing]);
    }
    if (text.weight !== undefined) {
      declarations.push([`--text-${size}--font-weight`, String(text.weight)]);
    }
  }
  return declarations;
}

export function zIndexDeclarations(): Declarations {
  return Object.entries(zIndex).map(
    ([layer, value]) => [`--z-${layer}`, String(value)] as const,
  );
}

function round(value: number): number {
  return Number(value.toFixed(4));
}

// shadcn bridges only values it reads as colors, and `transparent` isn't one.
function styleColor(color: StyleColor, tokens: ThemeTokens): string {
  if (color === 'transparent') {
    return formatColor({ alpha: 0, components: [0, 0, null], space: 'oklch' });
  }
  const role = tokens[color.role];
  if (role === undefined) throw new Error(`no token ${color.role}`);
  return formatColor({ ...role, alpha: (role.alpha ?? 1) * color.alpha });
}
